# Generated by Django 3.1.7 on 2021-03-16 12:27

from django.db import migrations, models
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210312_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=200, validators=[tracker.validators.validate_integers]),
        ),
    ]
