# Generated by Django 3.1.7 on 2021-04-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_update_users_in_project', 'Can update users in project')]},
        ),
    ]
