# Generated by Django 3.1.7 on 2021-04-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20210414_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_update_users_in_project', 'Can update users in project'), ('users_view', 'Users view')]},
        ),
    ]
